//! Format-drift conformance.
//!
//! `tests/corpus` is pinned by commit SHA and therefore goes stale *by design* —
//! that is what makes it a stable regression signal. This suite is the opposite:
//! it runs against lockfiles generated by whatever package-manager versions are
//! released **today**, via `scripts/format-drift.sh`, on a nightly schedule.
//!
//! The failure mode it exists to catch is silent under-reporting. A package
//! manager ships a new lockfile format, the parser stops understanding it, and
//! n3tra quietly reports fewer packages while still looking like it worked.
//! Without this, that surfaces as a user filing a false-negative bug in eighteen
//! months.
//!
//! So the assertion is not "parsing succeeded" — it is "we found a plausible
//! number of packages, and reported a gap if we could not".

#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::path::{Path, PathBuf};

fn drift_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/drift")
}

/// The generated fixtures declare a handful of direct dependencies whose
/// transitive closures are comfortably larger than this. A parser that
/// half-understands a new format will fall under it.
const MIN_PLAUSIBLE_PACKAGES: usize = 5;

#[test]
fn current_package_managers_produce_parsable_lockfiles() {
    let root = drift_root();
    if !root.exists() {
        eprintln!(
            "skipping: {} not present — run ./scripts/format-drift.sh",
            root.display()
        );
        return;
    }

    let mut checked = 0;
    let mut failures: Vec<String> = Vec::new();

    for entry in std::fs::read_dir(&root).expect("read drift dir").flatten() {
        let dir = entry.path();
        if !dir.is_dir() {
            continue;
        }
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        let inv = n3t_parse::scan(&dir, false);
        checked += 1;

        // A gap is an acceptable outcome: it means the parser recognized that it
        // did not understand the file, which is the designed behavior for a
        // format bump. Silent under-reporting is what must not happen.
        if !inv.gaps.is_empty() {
            failures.push(format!(
                "{name}: parser reported a gap against a CURRENT lockfile — the format \
                 has probably changed: {:?}",
                inv.gaps
            ));
            continue;
        }

        if inv.packages.len() < MIN_PLAUSIBLE_PACKAGES {
            failures.push(format!(
                "{name}: only {} package(s) parsed from a current lockfile with no gap \
                 reported — this is the silent under-reporting case",
                inv.packages.len()
            ));
            continue;
        }

        // Every package must be versioned, or advisory matching checks nothing.
        let unversioned = inv
            .packages
            .iter()
            .filter(|p| p.purl.version().is_none())
            .count();
        if unversioned > 0 {
            failures.push(format!(
                "{name}: {unversioned} package(s) parsed without a version"
            ));
            continue;
        }

        eprintln!("  ok  {name}: {} packages", inv.packages.len());
    }

    assert!(checked > 0, "drift directory present but empty");
    assert!(
        failures.is_empty(),
        "format drift detected:\n  {}",
        failures.join("\n  ")
    );
}
